[package]
name = "pbs"
version = "0.0.2"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Will-Shanks/pbs-rs"
description = "Safe FFI for PBSPro HPC job scheduler"
keywords = ["pbs", "hpc"]

[dependencies]
bindgen = { version = "0.61", optional = true }
libc = "0.2"
linked_list_c = { path = "../linked_list" } 
clap = { version = "4.0", features = ["derive"], optional = true}

[build-dependencies]
bindgen = { version = "0.61", optional = true }
