[package]
name = "pbs"
version = "0.0.2"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Will-Shanks/pbs-rs"
description = "Safe FFI for PBSPro HPC job scheduler"

[dependencies]
bindgen = "0.61"
libc = "0.2"
linked_list_c = "0.0.1" 
clap = { version = "4.0", features = ["derive"] } 

[build-dependencies]
bindgen = "0.61"
